name: Rust

on:
  push:
    branches: [ corpus ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Get wasm-pack    
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --release
    - name: Build web
      run: cd www && npm ci && npm run build
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        folder: www/dist
        branch: gh-pages
